[build]
  command = "ng build && ng run blogging-website:server"
  publish = "dist/blogging_website/browser"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/angular-runtime"
